packages:
  - packages/**
  - experimentals/**
  - '!**/test/**'
  - '!**/template-**'

link-workspace-packages: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi

prefer-workspace-packages: false

save-workspace-protocol: true

shared-workspace-lockfile: true
